### ISSUE TITLE
Operator overloading work plan

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-operator-overloading#20]
There's a lot to do to support operator overloading. Here's the list of tasks I see as coming next to move operator overloading forward. I hope to work through these incrementally, but if you're interested in helping, I'd really welcome it--just comment in this issue explaining what you're doing so I can give any additional context and avoid redundant work.

- [ ] Draw an initial, intermediate conclusion on the generality of `with operator from` statements (#14)
- [ ] Consider improving typability and ergonomics of classes with operator overloading (#5 cc @rbuckton @rbuckton)
- [ ] Document proposed interaction of operator overloading and Records/Tuples (cc @drosenwasser @rbuckton)
- [ ] Clarify PROTOSPEC.md, including the workings of [[OpenOperators]]. Focus the README on an intuitive introduction and PROTOSPEC with more details. (h/t Fabrice Bellard)
- [ ] Implement `with operators from` in a Babel PR (unclear when to consider landing)
- [ ] Add significantly more tests against experimental Babel transformation; if possible, develop them in test262 format
- [ ] Write a "prelude" explaining how existing operators are defined (h/t @erights)
- [ ] Write some more detailed libraries using operator overloading, to be used with early experimental implementations, to see how it works in larger code samples, including at least a BigDecimal implementation and a vector/matrix library.
- [ ] Improve and deepen cross-language comparison (#9)
- [ ] Draw an initial conclusion about whether square-bracket overloading would be included in the initial version
- [ ] Write initial spec text

With these tasks complete, I think we'll be ready to propose operator overloading for Stage 2.
